name: Generate Snake Animation

on:
  # Jalankan otomatis setiap 12 jam
  schedule:
    - cron: "0 */12 * * *"
  
  # Bisa juga dijalankan manual
  workflow_dispatch:
  
  # Jalankan saat push ke main
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      # Generate snake animation
      - name: Generate Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: rhmdcode
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
      
      # Push ke branch output
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
